// 18/07/2015

#ifndef __EFI_OS_IDENTIFICATION_H__
#define __EFI_OS_IDENTIFICATION_H__

// EFI_OS_IDENTIFICATION_PROTOCOL_GUID
#define EFI_OS_IDENTIFICATION_PROTOCOL_GUID \
  { 0xC5C5DA95, 0x7D5C, 0x45E6, { 0xB2, 0xF1, 0x3F, 0xD5, 0x2B, 0xB1, 0x00, 0x77 } }

// SET_OS_VENDOR
typedef
VOID
(EFIAPI *OS_VENDOR)(
  IN CHAR8  *OSName
  );

// SET_OS_NAME
typedef
VOID
(EFIAPI *OS_NAME)(
  IN CHAR8  *OSName
  );

// EFI_OS_IDENTIFICATION_PROTOCOL
typedef struct _EFI_OS_IDENTIFICATION_PROTOCOL {
  UINTN     Revision;
  OS_VENDOR OSVendor;
  OS_NAME   OSName;
} EFI_OS_IDENTIFICATION_PROTOCOL;

// gEfiOsIdentificationProtocolGuid
EFI_GUID gEfiOsIdentificationProtocolGuid;

#endif // ifndef __EFI_OS_IDENTIFICATION_H__
